# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitLs < Formula
  desc "list the files in the current directory along with a useful summary and helpful hyperlinks."
  homepage "https://github.com/llimllib/git-ls"
  version "7.0.1"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/llimllib/git-ls/releases/download/v7.0.1/git-ls_Darwin_x86_64.tar.gz"
      sha256 "e2dbe9b3bc3068efadaa96c89f17d1e90b56995f2b73edc5787c43c69ec9d6dc"

      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/llimllib/git-ls/releases/download/v7.0.1/git-ls_Darwin_arm64.tar.gz"
      sha256 "a2e87cf8244298b4fdf0cb09852eae91e051f2c9e802c64196a38490b254495f"

      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/llimllib/git-ls/releases/download/v7.0.1/git-ls_Linux_x86_64.tar.gz"
      sha256 "7a32e8c0f708fc53c900f7e158fbd1b88d17fabe0b8a3c749076242e5f4ea1a8"
      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/llimllib/git-ls/releases/download/v7.0.1/git-ls_Linux_arm64.tar.gz"
      sha256 "fa4dc3e1ddacdbb68f9156ad70219a41ac5698eb8a0a8d2263d0f0ac01303827"
      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
  end
end
